// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// raw2intC
IntegerVector raw2intC(CharacterVector vec);
RcppExport SEXP dipr_raw2intC(SEXP vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type vec(vecSEXP);
    rcpp_result_gen = Rcpp::wrap(raw2intC(vec));
    return rcpp_result_gen;
END_RCPP
}
// rollmeanimgC
NumericVector rollmeanimgC(SEXP obj, IntegerVector dim, int n);
RcppExport SEXP dipr_rollmeanimgC(SEXP objSEXP, SEXP dimSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rollmeanimgC(obj, dim, n));
    return rcpp_result_gen;
END_RCPP
}
// rollmedianimgC
NumericVector rollmedianimgC(SEXP obj, IntegerVector dim, int n);
RcppExport SEXP dipr_rollmedianimgC(SEXP objSEXP, SEXP dimSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rollmedianimgC(obj, dim, n));
    return rcpp_result_gen;
END_RCPP
}
// sfeaturesC
SEXP sfeaturesC(SEXP obj, SEXP ref, int nx, int ny, int nz);
RcppExport SEXP dipr_sfeaturesC(SEXP objSEXP, SEXP refSEXP, SEXP nxSEXP, SEXP nySEXP, SEXP nzSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< SEXP >::type ref(refSEXP);
    Rcpp::traits::input_parameter< int >::type nx(nxSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    Rcpp::traits::input_parameter< int >::type nz(nzSEXP);
    rcpp_result_gen = Rcpp::wrap(sfeaturesC(obj, ref, nx, ny, nz));
    return rcpp_result_gen;
END_RCPP
}
// sweepC
NumericVector sweepC(SEXP obj, SEXP m, IntegerVector dim, int op);
RcppExport SEXP dipr_sweepC(SEXP objSEXP, SEXP mSEXP, SEXP dimSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(sweepC(obj, m, dim, op));
    return rcpp_result_gen;
END_RCPP
}
