// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sweepC
NumericVector sweepC(SEXP obj, SEXP m, IntegerVector dim, int op);
RcppExport SEXP dipr_sweepC(SEXP objSEXP, SEXP mSEXP, SEXP dimSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< SEXP >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dim(dimSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    __result = Rcpp::wrap(sweepC(obj, m, dim, op));
    return __result;
END_RCPP
}
