# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Image roll mean
#'
#' @param obj An array.
#' @param dim Int vector.
#' @param n window.
#' @export
rollmeanimgC <- function(obj, dim, n) {
    .Call('dipr_rollmeanimgC', PACKAGE = 'dipr', obj, dim, n)
}

#' Image roll mean
#'
#' @param obj An array.
#' @param dim Int vector.
#' @param n window.
#' @export
rollmedianimgC <- function(obj, dim, n) {
    .Call('dipr_rollmedianimgC', PACKAGE = 'dipr', obj, dim, n)
}

#' Extract features
#'
#' @param obj An array.
#' @param ref A matrix.
#' @param nx x dimension.
#' @param ny y dimension.
#' @param nz z dimension.
#' @export
sfeaturesC <- function(obj, ref, nx, ny, nz) {
    .Call('dipr_sfeaturesC', PACKAGE = 'dipr', obj, ref, nx, ny, nz)
}

#' Multiply a number by two
#'
#' @param obj An array.
#' @param m A matrix.
#' @param dim Dimension.
#' @param op Operation, either - or *
#' @export
sweepC <- function(obj, m, dim, op) {
    .Call('dipr_sweepC', PACKAGE = 'dipr', obj, m, dim, op)
}

