# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sweep array with matrix
#'
#' @param obj An array.
#' @param m A matrix.
#' @param dim Dimension.
#' @param op Operation, either - or *
#' @export

sweepC <- function(obj, m, dim, op) {
    .Call('dipr_sweepC', PACKAGE = 'dipr', obj, m, dim, op)
}

